Attendence_System/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('attendence_sys.urls')),
    

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

attendence_sys/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views


from . import views

urlpatterns = [
    path('', views.home, name = 'home'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('searchattendence/', views.searchAttendence, name='searchattendence'),
    path('account/', views.facultyProfile, name='account'),
    # path('/',views.home, name ='addStudent')

    path('updateStudentRedirect/', views.updateStudentRedirect, name='updateStudentRedirect'),
    path('updateStudent/', views.updateStudent, name='updateStudent'),
    path('attendence/', views.takeAttendence, name='attendence'),
    path('register/',views.registerPage,name='register'),
    path('accounts/', include('allauth.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),
    # path('video_feed/', views.videoFeed, name='video_feed'),
    # path('videoFeed/', views.getVideo, name='videoFeed'),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),

]

attendence_sys/models.py
from django.db import models

from django.contrib.auth.models import User


def user_directory_path(instance, filename): 
    name, ext = filename.split(".")
    name = instance.firstname + instance.lastname
    filename = name +'.'+ ext 
    return 'Faculty_Images/{}'.format(filename)

class Faculty(models.Model):

    user = models.OneToOneField(User, null = True, blank = True, on_delete= models.CASCADE)
    firstname = models.CharField(max_length=200, null=True, blank=True)
    lastname = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    # profile_pic = models.ImageField(upload_to=user_directory_path ,null=True, blank=True)

    def __str__(self):
        return str(self.firstname + " " + self.lastname)


def student_directory_path(instance, filename):
    lst = filename.split(".")
    name, ext = lst[0],"jpg"
    name = instance.registration_id # + "_" + instance.branch + "_" + instance.year + "_" + instance.section
    filename = name +'.'+ ext 
    return 'Student_Images/{}/{}/{}/{}'.format(instance.branch,instance.year,instance.section,filename)

class Student(models.Model):

    BRANCH = (
        ('CSE','CSE'),
        ('IT','IT'),
        ('ECE','ECE'),
        ('CHEM','CHEM'),
        ('MECH','MECH'),
        ('EEE','EEE'),
        
    )
    YEAR = (
        ('1','1'),
        ('2','2'),
        ('3','3'),
        ('4','4'),
    )
    SECTION = (
        ('A','A'),
        ('B','B'),
        ('C','C'),
    )

    firstname = models.CharField(max_length=200, null=True, blank=True)
    lastname = models.CharField(max_length=200, null=True, blank=True)
    registration_id = models.CharField(max_length=200, null=True)
    branch = models.CharField(max_length=100, null=True, choices=BRANCH)
    year = models.CharField(max_length=100, null=True, choices=YEAR)
    section = models.CharField(max_length=100, null=True, choices=SECTION)
    profile_pic = models.ImageField(upload_to=student_directory_path ,null=True, blank=True)


    def __str__(self):
        return str(self.registration_id)

class Attendence(models.Model):
    # faculty = models.ForeignKey(Faculty, null = True, on_delete= models.SET_NULL)
    # student = models.ForeignKey(Student, null = True, on_delete= models.SET_NULL)
    Faculty_Name = models.CharField(max_length=200, null=True, blank=True)
    Student_ID = models.CharField(max_length=200, null=True, blank=True)
    date = models.DateField(auto_now_add = True, null = True)
    time = models.TimeField(auto_now_add=True, null = True)
    branch = models.CharField(max_length=200, null = True)
    year = models.CharField(max_length=200, null = True)
    section = models.CharField(max_length=200, null = True)
    period = models.CharField(max_length=200, null = True)
    status = models.CharField(max_length=200, null = True, default='Absent')

    def __str__(self):
        return str(self.Student_ID + "_" + str(self.date)+ "_" + str(self.period))

attendence_sys/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

from .models import *

class CreateStudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super(CreateStudentForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
    
class FacultyForm(ModelForm):
    class Meta:
        model = Faculty
        fields = '__all__'
        exclude = ['user']
    def __init__(self, *args, **kwargs):
        super(FacultyForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'    

class CreateUserForms(UserCreationForm):
    firstname = forms.CharField(max_length=50)
    lastname = forms.CharField(max_length=50)
    phone = forms.CharField(max_length=12)
    class Meta:
        model = User
        fields = ['username','firstname','lastname','phone','email','password1','password2']

attendence_sys/views.py
import re
from django.shortcuts import render, redirect
from django.http import HttpResponse, StreamingHttpResponse

from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from django.urls import reverse
from .forms import *
from django.contrib.auth.forms import UserCreationForm

from .models import Student, Attendence
from .filters import AttendenceFilter

# from django.views.decorators import gzip

from .recognizer import Recognizer
from datetime import date

def registerPage(request):
    form = CreateUserForms()

    if request.method == "POST":
        form = CreateUserForms(request.POST)
        if form.is_valid():
            form.save()
            fac = Faculty()
            fac.firstname = request.POST['firstname']
            fac.lastname = request.POST['lastname']
            fac.email = request.POST['email']
            fac.phone = request.POST['phone']
            fac.user = User.objects.get(username = request.POST['username'])
            fac.save()


    context = {'form':form}
    return render(request, 'attendence_sys/register.html', context)

# def register(request):
#     if request.method == "POST":
#         fm = CustomerRegistrationForm(request.POST)
#         if fm.is_valid():
#             fm.save()
#             email = request.POST.get('email')
#             return redirect(kwargs={'email_':str(email)})
#             # user = User.objects.get(email=request.POST.get('id_email'))
#             # new_customer = Customer()
#             # new_customer.user = user
#             # new_customer.name = user.first_name + user.last_name
            
#             # new_customer.save()
#     else:
#         fm = CustomerRegistrationForm()
#     return render(request,'attendence_sys/register.html',{'fm':fm})
    

@login_required(login_url = 'login')
def home(request):
    studentForm = CreateStudentForm()

    if request.method == 'POST':
        studentForm = CreateStudentForm(data = request.POST, files=request.FILES)
        # print(request.POST)
        stat = False 
        try:
            student = Student.objects.get(registration_id = request.POST['registration_id'])
            stat = True
        except:
            stat = False
        if studentForm.is_valid() and (stat == False):
            studentForm.save()
            name = studentForm.cleaned_data.get('firstname') +" " +studentForm.cleaned_data.get('lastname')
            messages.success(request, 'Student ' + name + ' was successfully added.')
            return redirect('home')
        else:
            messages.error(request, 'Student with Registration Id '+request.POST['registration_id']+' already exists.')
            return redirect('home')

    context = {'studentForm':studentForm}
    return render(request, 'attendence_sys/home.html', context)


def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username = username, password = password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'Username or Password is incorrect')

    context = {}
    return render(request, 'attendence_sys/login.html', context)

@login_required(login_url = 'login')
def logoutUser(request):
    logout(request)
    return redirect('login')

@login_required(login_url = 'login')
def updateStudentRedirect(request):
    context = {}
    if request.method == 'POST':
        try:
            reg_id = request.POST['reg_id']
            branch = request.POST['branch']
            student = Student.objects.get(registration_id = reg_id, branch = branch)
            updateStudentForm = CreateStudentForm(instance=student)
            context = {'form':updateStudentForm, 'prev_reg_id':reg_id, 'student':student}
        except:
            messages.error(request, 'Student Not Found')
            return redirect('home')
    return render(request, 'attendence_sys/student_update.html', context)

@login_required(login_url = 'login')
def updateStudent(request):
    if request.method == 'POST':
        context = {}
        try:
            student = Student.objects.get(registration_id = request.POST['prev_reg_id'])
            updateStudentForm = CreateStudentForm(data = request.POST, files=request.FILES, instance = student)
            if updateStudentForm.is_valid():
                updateStudentForm.save()
                messages.success(request, 'Updation Success')
                return redirect('home')
        except:
            messages.error(request, 'Updation Unsucessfull')
            return redirect('home')
    return render(request, 'attendence_sys/student_update.html', context)


@login_required(login_url = 'login')
def takeAttendence(request):
    if request.method == 'POST':
        details = {
            'branch':request.POST['branch'],
            'year': request.POST['year'],
            'section':request.POST['section'],
            'period':request.POST['period'],
            'faculty':request.user.faculty
            }
        if Attendence.objects.filter(date = str(date.today()),branch = details['branch'], year = details['year'], section = details['section'],period = details['period']).count() != 0 :
            messages.error(request, "Attendence already recorded.")
            return redirect('home')
        else:
            students = Student.objects.filter(branch = details['branch'], year = details['year'], section = details['section'])
            names = Recognizer(details)
            for student in students:
                if str(student.registration_id) in names:
                    attendence = Attendence(Faculty_Name = request.user.faculty, 
                    Student_ID = str(student.registration_id), 
                    period = details['period'], 
                    branch = details['branch'], 
                    year = details['year'], 
                    section = details['section'],
                    status = 'Present')
                    attendence.save()
                else:
                    attendence = Attendence(Faculty_Name = request.user.faculty, 
                    Student_ID = str(student.registration_id), 
                    period = details['period'],
                    branch = details['branch'], 
                    year = details['year'], 
                    section = details['section'])
                    attendence.save()
            attendences = Attendence.objects.filter(date = str(date.today()),branch = details['branch'], year = details['year'], section = details['section'],period = details['period'])
            context = {"attendences":attendences, "ta":True}
            messages.success(request, "Attendence taking Success")
            return render(request, 'attendence_sys/attendence.html', context)        
    context = {}
    return render(request, 'attendence_sys/home.html', context)

def searchAttendence(request):
    attendences = Attendence.objects.all()
    myFilter = AttendenceFilter(request.GET, queryset=attendences)
    attendences = myFilter.qs
    context = {'myFilter':myFilter, 'attendences': attendences, 'ta':False}
    return render(request, 'attendence_sys/attendence.html', context)


def facultyProfile(request):
    faculty = request.user.faculty
    form = FacultyForm(instance = faculty)
    context = {'form':form}
    return render(request, 'attendence_sys/facultyForm.html', context)


 
# class VideoCamera(object):
#     def __init__(self):
#         self.video = cv2.VideoCapture(0)
#     def __del__(self):
#         self.video.release()

#     def get_frame(self):
#         ret,image = self.video.read()
#         ret,jpeg = cv2.imencode('.jpg',image)
#         return jpeg.tobytes()


# def gen(camera):
#     while True:
#         frame = camera.get_frame()
#         yield(b'--frame\r\n'
#         b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')


# @gzip.gzip_page
# def videoFeed(request):
#     try:
#         return StreamingHttpResponse(gen(VideoCamera()),content_type="multipart/x-mixed-replace;boundary=frame")
#     except:
#         print("aborted")

# def getVideo(request):
#     return render(request, 'attendence_sys/videoFeed.html')

attendence_sys/templates/attendence_sys/addStudent.html
{% extends 'attendence_sys/main.html' %}

{% block content %}
<div class="container">
    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% else %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
    <style>
        .fname{
            
        }

    </style>

<div class="col-md-6" style="margin-top: 20px;">
    <div class="card card-body">
        <center><h3>Add Student</h3></center>
        <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group fname">
                        <label class="control-label">Enter First Name:</label>
                        {{ studentForm.firstname }}
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group lname">
                        <label class="control-label">Enter Last Name:</label>
                        {{ studentForm.lastname }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group reg">
                        <label class="control-label">Enter Registration ID:</label>
                        {{ studentForm.registration_id }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group bran">
                        <label for="sel1">Select Branch:</label>
                        {{ studentForm.branch }}
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group year">
                        <label for="sel1">Select Year:</label>
                        {{ studentForm.year }}
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group sec">
                        <label for="sel1">Select Section:</label>
                        {{ studentForm.section }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <div class="form-group" style="border: none;">
                        <label class="control-label">Upload Profile Picture:</label>
                        {{ studentForm.profile_pic }}
                    </div>
                </div>
                <div class="col-md-3"></div>
            </div>
            <button type="submit" class="btn btn-block btn-info">Submit</button>    
        </form>
    </div>
</div>
</div>

{% endblock %}

attendence_sys/templates/attendence_sys/navbar.html
{% load static %}


<style>
  nav {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    z-index: 100;
    height: 147px;
}
  img {
  vertical-align: middle;
  border-style: outset;
  width: 85px;
  height: 87px;
  margin-left: 47px;
}
  .hello-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
  body{
    background-color:#ecede9;
  }

    .as{
      color:black;
    }
    label.control-label {
      margin-top: 10px;
  }
      input#id_firstname {
        height: 44px;
        width: 306px;
        margin-right: 282px;
        margin-top: 17px;
        padding: 13px;
    }
    input#id_lastname {
      height: 44px;
      width: 306px;
      margin-right: -137px;
      margin-top: 17px;
      padding: 13px;
  }

    .card {
      position: relative;
      display: -ms-flexbox;
      display: flex;
      -ms-flex-direction: column;
      flex-direction: column;
      min-width: 0;
      word-wrap: break-word;
      background-color: #570a7b;
      background-clip: border-box;
      border: 1px solid rgba(0,0,0,.125);
      border-radius: .25rem;
      color: #ecede9;
    }
  
    .btn-info {
      color: #000;
      background-color: #ecede9;
      border-color:#ecede9;
      margin-top: 69px;
        align-items: center;
        width: 589px;
    height: 77px;
    }
    .nav-link{
      color: black;
      background-color:#ff9400;
      margin: 6px;
    }
    .name{
      color: white;

    }
    .form-group {
      margin-bottom: 1rem;
      width: 533px;
  }
  .nav-link.home {
    margin-top: -70px;
    width: 101px;
    padding: 0px;
    color:white;
}
.nav-link.hello {
  margin-top: -16px;
    width: 216px;
    padding: 5px;
    color:white;
}
.nav-link.account {
  margin-top: -70px;
  width: 101px;
  padding: 0px;
  color:white;
}
.nav-link.logout {
  margin-top: -70px;
  width: 101px;
  padding: 0px;
  color:white;
}

 

</style>
<style>
  $main-green: #53f765;
$main-yellow: #fffd35;
$main-orange: #ff9c00;
$main-red: #ff3368;
$main-blue: #32f8ff;
$main-darkblue: #324fff;
$margin: 1.375rem;


// Glitch
.glitch {
  color: white;
  line-height: 1;
}
span.glitch.character {
  color: white;
}
.characters-container {
  position: relative;
  margin: $margin/2 0;
}

.character {
  display: inline-block;
  position: relative;
  letter-spacing: -$margin/1.5;
}

.character:nth-child(even) {
  bottom: $margin/3;
}

@-webkit-keyframes glitch-animation-after {
  0% {
    clip: rect(15px, 600px, 100px, 0)
  }
  6.66667% {
    clip: rect(6px, 600px, 94px, 0)
  }
  13.33333% {
    clip: rect(28px, 600px, 58px, 0)
  }
  20% {
    clip: rect(32px, 600px, 37px, 0)
  }
  26.66667% {
    clip: rect(76px, 600px, 39px, 0)
  }
  33.33333% {
    clip: rect(74px, 600px, 36px, 0)
  }
  40% {
    clip: rect(81px, 600px, 34px, 0)
  }
  46.66667% {
    clip: rect(54px, 600px, 14px, 0)
  }
  53.33333% {
    clip: rect(65px, 600px, 50px, 0)
  }
  60% {
    clip: rect(85px, 600px, 100px, 0)
  }
  66.66667% {
    clip: rect(61px, 600px, 72px, 0)
  }
  73.33333% {
    clip: rect(23px, 600px, 65px, 0)
  }
  80% {
    clip: rect(0, 0, 0, 0)
  }
  100% {
    clip: rect(0, 0, 0, 0)
  }
}

@keyframes glitch-animation-after {
  0% {
    clip: rect(65px, 600px, 39px, 0)
  }
  6.66667% {
    clip: rect(19px, 600px, 21px, 0)
  }
  13.33333% {
    clip: rect(80px, 600px, 51px, 0)
  }
  20% {
    clip: rect(6px, 600px, 16px, 0)
  }
  26.66667% {
    clip: rect(31px, 600px, 95px, 0)
  }
  33.33333% {
    clip: rect(94px, 600px, 84px, 0)
  }
  40% {
    clip: rect(84px, 600px, 74px, 0)
  }
  46.66667% {
    clip: rect(97px, 600px, 55px, 0)
  }
  53.33333% {
    clip: rect(7px, 600px, 18px, 0)
  }
  60% {
    clip: rect(24px, 600px, 17px, 0)
  }
  66.66667% {
    clip: rect(28px, 600px, 97px, 0)
  }
  73.33333% {
    clip: rect(61px, 600px, 2px, 0)
  }
  80% {
    clip: rect(0, 0, 0, 0)
  }
  100% {
    clip: rect(0, 0, 0, 0)
  }
}

@-webkit-keyframes glitch-animation-before {
  0% {
    clip: rect(62px, 600px, 45px, 0)
  }
  6.66667% {
    clip: rect(46px, 600px, 67px, 0)
  }
  13.33333% {
    clip: rect(68px, 600px, 49px, 0)
  }
  20% {
    clip: rect(82px, 600px, 56px, 0)
  }
  26.66667% {
    clip: rect(53px, 600px, 6px, 0)
  }
  33.33333% {
    clip: rect(9px, 600px, 90px, 0)
  }
  40% {
    clip: rect(95px, 600px, 69px, 0)
  }
  46.66667% {
    clip: rect(50px, 600px, 99px, 0)
  }
  53.33333% {
    clip: rect(4px, 600px, 60px, 0)
  }
  60% {
    clip: rect(78px, 600px, 97px, 0)
  }
  66.66667% {
    clip: rect(30px, 600px, 69px, 0)
  }
  73.33333% {
    clip: rect(68px, 600px, 49px, 0)
  }
  80% {
    clip: rect(0, 0, 0, 0)
  }
  100% {
    clip: rect(0, 0, 0, 0)
  }
}

@keyframes glitch-animation-before {
  0% {
    clip: rect(86px, 600px, 98px, 0)
  }
  6.66667% {
    clip: rect(62px, 600px, 92px, 0)
  }
  13.33333% {
    clip: rect(91px, 600px, 20px, 0)
  }
  20% {
    clip: rect(47px, 600px, 44px, 0)
  }
  26.66667% {
    clip: rect(1px, 600px, 77px, 0)
  }
  33.33333% {
    clip: rect(99px, 600px, 22px, 0)
  }
  40% {
    clip: rect(44px, 600px, 12px, 0)
  }
  46.66667% {
    clip: rect(71px, 600px, 65px, 0)
  }
  53.33333% {
    clip: rect(52px, 600px, 28px, 0)
  }
  60% {
    clip: rect(10px, 600px, 15px, 0)
  }
  66.66667% {
    clip: rect(75px, 600px, 69px, 0)
  }
  73.33333% {
    clip: rect(57px, 600px, 62px, 0)
  }
  80% {
    clip: rect(0, 0, 0, 0)
  }
  100% {
    clip: rect(0, 0, 0, 0)
  }
}

.glitch:before,
.glitch:after {
  content: attr(data-text);
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  background: rgba(204, 57, 107, 0);
  clip: rect(0, 0, 0, 0);
}

.glitch:after {
  left: 2px;
  text-shadow: -5px 0 rgba(255, 51, 104, 0.5);
  animation: glitch-animation-after 2s infinite linear alternate-reverse;
}

.glitch:before {
  left: -2px;
  text-shadow: 5px 0 rgba(94, 38, 255, 0.5);
  animation: glitch-animation-before 3s infinite linear alternate-reverse;
}

// Styling
body {
  background: black;
}

.page-title {
  font-family: 'Verdana';
  font-weight: bold;
  font-size: 3em;
}

</style>



<nav class="navbar navbar-expand-lg" style= "background:transparent">
  
   <img src="{% static 'images/logo.jpg' %}" height="50px" width="250px">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    
  <h1 class="page-title">
    <div class="title-glitch-top">
      <span class="glitch character" data-text="B">D</span>
      <span class="glitch character" data-text="A">S</span>
      <span class="glitch character" data-text=""></span>
      <span class="glitch character" data-text="A">A</span>
      <span class="glitch character" data-text="T">T</span>
      <span class="glitch character" data-text="T">T</span>
      <span class="glitch character" data-text="E">E</span>
      <span class="glitch character" data-text="N">N</span>
      <span class="glitch character" data-text="D">D</span>
      <span class="glitch character" data-text="E">E</span>
      <span class="glitch character" data-text="N">N</span>
      <span class="glitch character" data-text="C">C</span>
      <span class="glitch character" data-text="E">E</span>
      <span class="glitch character" data-text=""></span>
      <span class="glitch character" data-text="S">S</span>
      <span class="glitch character" data-text="Y">Y</span>
      <span class="glitch character" data-text="S">S</span>
      <span class="glitch character" data-text="T">T</span>
      <span class="glitch character" data-text="E">E</span>
      <span class="glitch character" data-text="M">M</span>
    </div>
  </h1>
    {% comment %} title><h1 class="heading" align="center">DS ATTENDENCE SYSTEM</h1></title> {% endcomment %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <span class="nav-link hello">Hello, {{ request.user.faculty }}</span>
      </li>
      <li class="nav-item active">
        <a href="{% url 'home' %}" class="nav-link home">Home</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link account" href="{% url 'account' %}">Account</a>
      </li>
      <li class="nav-item">
        <a class="nav-link logout" href="{% url 'logout' %}">Logout</a>
      </li>
    </ul>
  </div>
</nav>

{% comment %} {% load static %}


<style>
  .hello-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
  body{
    background-color:#ecede9;
  }

    .card {
      position: relative;
      display: -ms-flexbox;
      display: flex;
      -ms-flex-direction: column;
      flex-direction: column;
      min-width: 0;
      word-wrap: break-word;
      background-color: #570a7b;
      background-clip: border-box;
      border: 1px solid rgba(0,0,0,.125);
      border-radius: .25rem;
      color: #ecede9;
    }
  
    .btn-info {
      color: #000;
      background-color: #ecede9;
      border-color:#ecede9;
      margin-top: 139px;
        align-items: center;
    }
    .nav-link{
      color: black;
      background-color: yellow;
      margin: -6px;
    }
    .name{
      color: white;

    }
</style>

<nav class="navbar navbar-expand-lg" style= "background-color:black">
 <img src="{% static 'images/logo.jpg' %}" height="50px" width="250px">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <span class="nav-link name">Hello, {{ request.user.faculty }}</span>
      </li>
      <li class="nav-item active">
        <a href="{% url 'home' %}" class="nav-link">Home</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'account' %}">Account</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
    </ul>
  </div>
</nav>  {% endcomment %}

attendence_sys/templates/attendence_sys/videoFeed.html
{% extends 'attendence_sys/main.html' %}

{% block content %}
    <img src="{% url 'video_feed' %}">
{% endblock %}